# Generated by Django 4.1.2 on 2022-10-22 17:29

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("translation", models.CharField(max_length=255)),
                ("text_language", models.CharField(blank=True, max_length=2)),
                ("text_locale", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SentenceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=2500)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentences",
                    models.ManyToManyField(
                        blank=True, to="leasikApp.sentence"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "played_lists",
                    models.ManyToManyField(to="leasikApp.sentencelist"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sentence",
            name="tags",
            field=models.ManyToManyField(to="leasikApp.tag"),
        ),
        migrations.CreateModel(
            name="WordCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                (
                    "repetition_number",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                ("easiness_factor", models.FloatField(default=2.5)),
                (
                    "inter_repetition_interval",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(0)
                            )
                        ],
                        verbose_name="inter-repetition interval",
                    ),
                ),
                ("last_review_date", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentence_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leasikApp.sentencelist",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "sentence_list", "word")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="sentence",
            unique_together={("text", "translation")},
        ),
    ]
