# Generated by Django 4.0 on 2022-01-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='sentences',
        ),
    ]
