# Generated by Django 4.0.1 on 2022-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sentencelist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sentencelist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sentencelist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sentencelist',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
