# Generated by Django 4.1.2 on 2022-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wordcard",
            unique_together=set(),
        ),
    ]
