# Generated by Django 4.0.1 on 2022-01-17 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasikApp", "0002_alter_sentencelist_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proficiency",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="sentencenote",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="proficiency",
            unique_together={("owner", "sentence")},
        ),
        migrations.AlterUniqueTogether(
            name="sentencenote",
            unique_together={("sentence", "owner")},
        ),
    ]
