# Generated by Django 4.1.2 on 2022-11-03 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasikApp", "0002_alter_wordcard_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wordcard",
            unique_together={("owner", "sentence_list", "word")},
        ),
    ]
