# Generated by Django 4.0.5 on 2022-06-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0003_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='sentence',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='card',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='leasikApp.card'),
            preserve_default=False,
        ),
    ]
