# Generated by Django 4.2.2 on 2023-07-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0003_alter_wordcard_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordcard",
            name="easiness_factor",
            field=models.FloatField(default=1.3),
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leasikApp.sentence",
                    ),
                ),
            ],
        ),
    ]
