# Generated by Django 4.0 on 2022-01-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0003_sentence_sentence_id_alter_sentence_sentence_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='sentence_text',
        ),
    ]
