# Generated by Django 4.0 on 2022-01-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0004_remove_sentence_sentence_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sentences',
            field=models.ManyToManyField(to='leasikApp.Sentence'),
        ),
    ]
