# Generated by Django 4.0.5 on 2022-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0004_remove_bookmark_sentence_bookmark_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
