# Generated by Django 4.2.2 on 2023-07-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0004_alter_wordcard_easiness_factor_word"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("word", "sentence")},
        ),
    ]
