# Generated by Django 4.1 on 2022-08-29 12:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasikApp", "0005_card_is_bookmarked_delete_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                (
                    "repetition_number",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                ("easiness_factor", models.FloatField(default=2.5)),
                (
                    "inter_repetition_interval",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(0)
                            )
                        ],
                        verbose_name="inter-repetition interval",
                    ),
                ),
                ("last_review_date", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentence_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leasikApp.sentencelist",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "sentence_list", "word")},
            },
        ),
        migrations.DeleteModel(
            name="Card",
        ),
    ]
