# Generated by Django 4.0 on 2022-01-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leasikApp', '0006_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('name', 'owner')},
        ),
    ]
