# Generated by Django 4.0.2 on 2022-02-03 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasikApp", "0007_sentencelist_bookmarked_sentences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentencelist",
            name="bookmarked_sentences",
        ),
        migrations.CreateModel(
            name="SentenceBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentence_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leasikApp.sentencelist",
                    ),
                ),
                (
                    "sentences",
                    models.ManyToManyField(
                        blank=True, to="leasikApp.Sentence"
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "sentence_list")},
            },
        ),
    ]
