# Generated by Django 4.0 on 2022-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leasikApp', '0007_alter_list_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('slug', 'owner')},
        ),
    ]
