# Generated by Django 4.2.2 on 2023-07-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0007_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="played_lists",
        ),
        migrations.AlterUniqueTogether(
            name="wordcard",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wordcard",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="wordcard",
            name="sentence_list",
        ),
        migrations.DeleteModel(
            name="SentenceList",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="WordCard",
        ),
    ]
