# Generated by Django 4.0.2 on 2022-02-03 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "leasikApp",
            "0009_alter_card_unique_together_card_hidden_word_position",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="card",
            unique_together={("owner", "sentence", "hidden_word_position")},
        ),
    ]
