# Generated by Django 4.0.1 on 2022-01-05 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasikApp', '0009_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasikApp.word'),
        ),
    ]
