# Generated by Django 4.1 on 2022-09-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0009_tag_sentence_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sentence",
            old_name="tag",
            new_name="tags",
        ),
    ]
