# Generated by Django 4.1 on 2022-09-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0010_rename_tag_sentence_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
