# Generated by Django 4.0.1 on 2022-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0010_alter_proficiency_user_alter_proficiency_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='english_translation',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='text',
            field=models.TextField(editable=False, null=True),
        ),
    ]
