# Generated by Django 4.1.1 on 2022-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0011_alter_tag_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="language",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
