# Generated by Django 4.0.2 on 2022-02-16 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasikApp", "0011_remove_sentencebookmark_sentences_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SentenceBookmark",
            new_name="Bookmark",
        ),
    ]
