# Generated by Django 4.0.1 on 2022-01-06 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_studying_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='questions_per_page',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
