# Generated by Django 4.1.1 on 2022-09-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0012_sentence_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sentence",
            old_name="language",
            new_name="text_language",
        ),
    ]
