# Generated by Django 4.1.1 on 2022-10-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasikApp", "0013_rename_language_sentence_text_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="text_locale",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
