# Generated by Django 4.0.1 on 2022-01-06 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0013_alter_userprofile_current_studying_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='questions_per_page',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
