# Generated by Django 4.0.1 on 2022-01-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0014_alter_userprofile_questions_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='words',
            field=models.ManyToManyField(blank=True, to='leasikApp.Word'),
        ),
    ]
