# Generated by Django 4.0.1 on 2022-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0015_alter_list_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfContainedSentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('english_translation', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='sentences',
            field=models.ManyToManyField(to='leasikApp.SelfContainedSentence'),
        ),
    ]
