# Generated by Django 4.0.1 on 2022-01-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasikApp', '0016_selfcontainedsentence_alter_word_sentences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sentences',
            field=models.ManyToManyField(blank=True, to='leasikApp.SelfContainedSentence'),
        ),
        migrations.AlterUniqueTogether(
            name='selfcontainedsentence',
            unique_together={('text', 'english_translation')},
        ),
        migrations.CreateModel(
            name='SentenceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentences', models.ManyToManyField(blank=True, to='leasikApp.SelfContainedSentence')),
            ],
            options={
                'unique_together': {('slug', 'owner')},
            },
        ),
    ]
