# Generated by Django 4.0.1 on 2022-01-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0019_alter_sentenceproficiency_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='list',
            name='words',
        ),
        migrations.AlterUniqueTogether(
            name='proficiency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='word',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='word',
            name='sentences',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Proficiency',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
