# Generated by Django 4.0.1 on 2022-01-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0020_alter_list_unique_together_remove_list_owner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelfContainedSentence',
            new_name='Sentence',
        ),
    ]
