# Generated by Django 4.0.1 on 2022-01-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0021_rename_selfcontainedsentence_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='sentence_id',
            new_name='id',
        ),
    ]
