# Generated by Django 4.0.1 on 2022-01-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0023_alter_sentence_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='english_translation',
            new_name='translation',
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('text', 'translation')},
        ),
    ]
