# Generated by Django 4.0.1 on 2022-01-10 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasikApp', '0024_rename_english_translation_sentence_translation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentenceList',
            new_name='List',
        ),
    ]
