# Generated by Django 4.0.1 on 2022-01-10 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasikApp', '0025_rename_sentencelist_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentenceProficiency',
            new_name='Proficiency',
        ),
    ]
