# Generated by Django 4.0.1 on 2022-01-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0026_rename_sentenceproficiency_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_studying_language',
        ),
    ]
