# Generated by Django 4.0.1 on 2022-01-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0027_remove_userprofile_current_studying_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proficiency',
            options={'verbose_name_plural': 'proficiencies'},
        ),
    ]
