# Generated by Django 4.0.1 on 2022-01-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0028_alter_proficiency_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='questions_per_page',
        ),
    ]
