# Generated by Django 4.0.1 on 2022-01-12 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasikApp', '0029_remove_userprofile_questions_per_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='SentenceList',
        ),
    ]
