# Generated by Django 4.0.1 on 2022-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0030_rename_list_sentencelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('sentences', models.ManyToManyField(blank=True, to='leasikApp.Sentence')),
            ],
        ),
    ]
