# Generated by Django 4.0.1 on 2022-01-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0031_sentencenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentencenote',
            name='sentences',
        ),
        migrations.AddField(
            model_name='sentencenote',
            name='sentence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leasikApp.sentence'),
            preserve_default=False,
        ),
    ]
