# Generated by Django 4.0.1 on 2022-01-13 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leasikApp', '0032_remove_sentencenote_sentences_sentencenote_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencenote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sentencenote',
            unique_together={('sentence', 'user')},
        ),
    ]
