# Generated by Django 4.0.1 on 2022-01-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasikApp', '0033_sentencenote_user_alter_sentencenote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencenote',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
